name: Deploy Azure Function App & Infra

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy infrastructure (Bicep)
        uses: azure/arm-deploy@v1
        with:
          scope: resourcegroup
          subscriptionId: ${{ fromJSON(secrets.AZURE_CREDENTIALS).subscriptionId }}
          resourceGroupName: rg-order-logic-northeurope
          template: ./infra/main.bicep
          parameters: location='northeurope'

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run:  dotnet restore ./queue-function

      - name: Build project
        run: dotnet build ./queue-function --configuration Release

      - name: Deploy Azure Function
        uses: Azure/functions-action@v1
        with:
          app-name: orderprocessorfunc
          package: ./queue-function/bin/Release/net8.0/publish
