name: Deploy Azure Function App & Infra

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Bicep template with Azure CLI
        run: |
          az deployment group create \
          --name deploy-${{ github.run_number }} \
          --resource-group rg-order-logic-northeurope \
          --template-file ./infra/main.bicep \
          --parameters location='northeurope'

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run:  dotnet restore ./queue-function

      - name: Build project
        run: dotnet build ./queue-function --configuration Release

      - name: Publish function app
        run: dotnet publish ./queue-function --configuration Release --output ./publish

      - name: Deploy Azure Function
        uses: Azure/functions-action@v1
        with:
          app-name: orderprocessorfunc
          package: ./publish
